apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  root-password: cm9vdHBhc3N3b3Jk #rootpassword
  database: d29yZHByZXNz #wordpress
  username: d29yZHByZXNz #wordpress
  password: d29yZHByZXNzUGFzc3dvcmQ= #wordpressPassword
